Main readme and build + test workflow

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -10,22 +10,50 @@ name: Java CI with Maven
 
 on:
   push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-
+    branches:
+      - 'main'
+      - '*'
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
     - name: Set up JDK 21
-      uses: actions/setup-java@v3
+      uses: actions/setup-java@v4
       with:
         java-version: '21'
         distribution: 'temurin'
         cache: maven
     - name: Build with Maven
       run: mvn -B package --file pom.xml
+
+
+  run-test:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Set up JDK 21
+      uses: actions/setup-java@v4
+      with:
+        java-version: '21'
+        distribution: 'temurin'
+        cache: maven
+
+    # On execute les tests sans interruption
+    - name: Run tests
+      run: mvn clean test
+      continue-on-error: true
+
+    - name: Check if tests passed
+      if: ${{ failure() }}
+      run: echo "::error line=1::Test check failed" && exit 1
+
+  coverages:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Run tests with Maven and generate coverage report
+      run: mvn clean test jacoco:report
+
+    - name: Check code coverage
+      id: check-coverage
+      run: mvn clean verify jacoco:report || echo "::error line=1::Coverage checks have not been met" && exit 1
