Update checkout maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -73,9 +73,13 @@ jobs:
   coverages:
     runs-on: ubuntu-latest
     steps:
-    - name: Run tests with Maven and generate coverage report
-      run: mvn clean test jacoco:report
-
-    - name: Check code coverage
-      id: check-coverage
-      run: mvn clean verify jacoco:report || echo "::error line=1::Coverage checks have not been met" && exit 1
+    # Vérification usuelles
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        
+      - name: Run tests with Maven and generate coverage report
+        run: mvn clean test jacoco:report
+  
+      - name: Check code coverage
+        id: check-coverage
+        run: mvn clean verify jacoco:report || echo "::error line=1::Coverage checks have not been met" && exit 1
